<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <RootNamespace>RetroDownfall.Arcanum.Secrets</RootNamespace>

    <AssemblyName>RetroDownfall.Arcanum.Secrets</AssemblyName>

    <IsAotCompatible>true</IsAotCompatible>

    <IsTrimmable>true</IsTrimmable>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

  </PropertyGroup>

  <ItemGroup>

    <InternalsVisibleTo Include="RetroDownfall.Arcanum.Tests" />

    <InternalsVisibleTo Include="RetroDownfall.TheForge.Tests" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Bcl.Memory" Version="10.0.10" />
  </ItemGroup>

</Project>
