using System.Text.Json.Serialization;
using RetroDownfall.Arcanum.Api.Intelligence;
using RetroDownfall.Arcanum.Api.Intelligence.OpenAi;
using RetroDownfall.Arcanum.Core.CommLink;
using RetroDownfall.Arcanum.Core.Chronosync;
using RetroDownfall.Arcanum.Core.Intelligence;
using RetroDownfall.Arcanum.Core.Intelligence.Models;
using RetroDownfall.Arcanum.Core.Pattern.Entities;
using RetroDownfall.Arcanum.Core.Primitives;
using RetroDownfall.Arcanum.Core.Storage;

namespace RetroDownfall.Arcanum.Api.Serialization;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ApiResponse<string>))]
[JsonSerializable(typeof(ApiResponse<bool>))]
[JsonSerializable(typeof(Result<string>))]
[JsonSerializable(typeof(Result<bool>))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(Error))]
[JsonSerializable(typeof(PingRequest))]
[JsonSerializable(typeof(OptionalWorkspaceRequest))]
[JsonSerializable(typeof(CoreChatMessage))]
[JsonSerializable(typeof(List<CoreChatMessage>))]
[JsonSerializable(typeof(ChronosyncReport))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(AttachedFileDto))]
[JsonSerializable(typeof(List<AttachedFileDto>))]
[JsonSerializable(typeof(SubmitHumanResponseRequest))]
[JsonSerializable(typeof(PatternSnapshot))]
[JsonSerializable(typeof(ApiResponse<PatternSnapshot>))]
[JsonSerializable(typeof(Result<PatternSnapshot>))]
[JsonSerializable(typeof(DomainType))]
[JsonSerializable(typeof(IntelligenceEventType))]
[JsonSerializable(typeof(IntelligenceEvent))]
[JsonSerializable(typeof(McpServerStatusDto))]
[JsonSerializable(typeof(WorkspaceArsenalDto))]
[JsonSerializable(typeof(ApiResponse<WorkspaceArsenalDto>))]
[JsonSerializable(typeof(Result<WorkspaceArsenalDto>))]
[JsonSerializable(typeof(List<McpServerStatusDto>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(ConversationSummaryDto))]
[JsonSerializable(typeof(List<ConversationSummaryDto>))]
[JsonSerializable(typeof(ApiResponse<List<ConversationSummaryDto>>))]
[JsonSerializable(typeof(ConversationDetailDto))]
[JsonSerializable(typeof(ApiResponse<ConversationDetailDto>))]
[JsonSerializable(typeof(Result<ConversationDetailDto>))]
[JsonSerializable(typeof(ConversationMessageDto))]
[JsonSerializable(typeof(List<ConversationMessageDto>))]
[JsonSerializable(typeof(ApiResponse<List<ConversationMessageDto>>))]
[JsonSerializable(typeof(Result<List<ConversationMessageDto>>))]
[JsonSerializable(typeof(MessageRole))]
[JsonSerializable(typeof(LoreDto))]
[JsonSerializable(typeof(List<LoreDto>))]
[JsonSerializable(typeof(UpsertLoreRequest))]
[JsonSerializable(typeof(ApiResponse<LoreDto>))]
[JsonSerializable(typeof(ApiResponse<List<LoreDto>>))]
[JsonSerializable(typeof(Result<LoreDto>))]
[JsonSerializable(typeof(OpenAiChatRequest))]
[JsonSerializable(typeof(OpenAiChatMessage))]
[JsonSerializable(typeof(List<OpenAiChatMessage>))]
[JsonSerializable(typeof(OpenAiMessageContent))]
[JsonSerializable(typeof(OpenAiContentPart))]
[JsonSerializable(typeof(OpenAiContentPart[]))]
[JsonSerializable(typeof(OpenAiImageUrl))]
[JsonSerializable(typeof(OpenAiToolCall))]
[JsonSerializable(typeof(OpenAiToolCall[]))]
[JsonSerializable(typeof(OpenAiStreamToolCall))]
[JsonSerializable(typeof(OpenAiStreamToolCall[]))]
[JsonSerializable(typeof(OpenAiFunctionCall))]
[JsonSerializable(typeof(OpenAiStreamOptions))]
[JsonSerializable(typeof(OpenAiResponseFormat))]
[JsonSerializable(typeof(OpenAiToolDefinition))]
[JsonSerializable(typeof(OpenAiToolDefinition[]))]
[JsonSerializable(typeof(OpenAiFunctionDefinition))]
[JsonSerializable(typeof(OpenAiChatResponse))]
[JsonSerializable(typeof(OpenAiChatChoice))]
[JsonSerializable(typeof(List<OpenAiChatChoice>))]
[JsonSerializable(typeof(OpenAiChatAssistantMessage))]
[JsonSerializable(typeof(ChatCompletionUsage))]
[JsonSerializable(typeof(OpenAiChatChunk))]
[JsonSerializable(typeof(OpenAiChatStreamChoice))]
[JsonSerializable(typeof(List<OpenAiChatStreamChoice>))]
[JsonSerializable(typeof(OpenAiDelta))]
[JsonSerializable(typeof(OpenAiErrorDetail))]
[JsonSerializable(typeof(OpenAiErrorResponse))]
[JsonSerializable(typeof(OpenAiModel))]
[JsonSerializable(typeof(OpenAiModelListResponse))]
[JsonSerializable(typeof(List<OpenAiModel>))]
[JsonSerializable(typeof(PromptResponseDto))]
[JsonSerializable(typeof(PromptToolCall))]
[JsonSerializable(typeof(List<PromptToolCall>))]
[JsonSerializable(typeof(ApiResponse<PromptResponseDto>))]
[JsonSerializable(typeof(Result<PromptResponseDto>))]
[JsonSerializable(typeof(IntelligenceToolCallEvent))]
[JsonSerializable(typeof(UnseenServantJobStatusDto))]
[JsonSerializable(typeof(UnseenServantJobStatusDto[]))]
[JsonSerializable(typeof(AdjustInitiativeRequestDto))]
[JsonSerializable(typeof(ApiResponse<UnseenServantJobStatusDto[]>))]
[JsonSerializable(typeof(Result<UnseenServantJobStatusDto[]>))]
[JsonSerializable(typeof(ApiResponse<UnseenServantJobStatusDto>))]
[JsonSerializable(typeof(Result<UnseenServantJobStatusDto>))]
[JsonSerializable(typeof(CommLinkMessageRequestDto))]
[JsonSerializable(typeof(CommLinkSeverity))]
[JsonSerializable(typeof(SemanticSpellResponse))]

public partial class ArcanumJsonContext : JsonSerializerContext;
