<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>Exe</OutputType>

    <IsAotCompatible>true</IsAotCompatible>

    <EFOptimizeContext>false</EFOptimizeContext>

  </PropertyGroup>

  <ItemGroup>

    <FrameworkReference Include="Microsoft.AspNetCore.App" />

  </ItemGroup>

  <ItemGroup>

    <ProjectReference Include="..\RetroDownfall.Arcanum.Api\RetroDownfall.Arcanum.Api.csproj" />

    <ProjectReference Include="..\RetroDownfall.Arcanum.Core\RetroDownfall.Arcanum.Core.csproj" />

    <ProjectReference Include="..\RetroDownfall.Arcanum.Infrastructure\RetroDownfall.Arcanum.Infrastructure.csproj" />

  </ItemGroup>

</Project>
