<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>WinExe</OutputType>

    <Version>0.1.0-alpha</Version>

    <RootNamespace>RetroDownfall.TheForge.Ux</RootNamespace>

    <AssemblyName>RetroDownfall.TheForge.Ux</AssemblyName>

    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

    <ApplicationManifest>app.manifest</ApplicationManifest>

    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Avalonia" Version="11.3.16" />

    <PackageReference Include="Avalonia.Desktop" Version="11.3.16" />

    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.16" />

    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.16" />

    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.16" Condition="'$(Configuration)' == 'Debug'" />

    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.4.1" />

    <PackageReference Include="ColorCode.Core" Version="2.0.15" />

    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />

    <PackageReference Include="Markdig" Version="1.2.0" />

    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />

    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />

    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />

    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />

    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />

    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />

    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />

    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />

  </ItemGroup>

  <ItemGroup>

    <ProjectReference Include="..\RetroDownfall.TheForge.Core\RetroDownfall.TheForge.Core.csproj" />

  </ItemGroup>

  <ItemGroup>

    <InternalsVisibleTo Include="RetroDownfall.TheForge.Tests" />

  </ItemGroup>

</Project>
