using System.Text.Json.Serialization;
using RetroDownfall.Arcanum.Core.Configuration;
using RetroDownfall.Arcanum.Core.Intelligence;
using RetroDownfall.Arcanum.Core.Logging;
using RetroDownfall.Arcanum.Core.Primitives;

namespace RetroDownfall.Arcanum.Core.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    WriteIndented = true)]
[JsonSerializable(typeof(ArcanumConfigurationFile))]
[JsonSerializable(typeof(ArcanumSettings))]
[JsonSerializable(typeof(RetentionSettings))]
[JsonSerializable(typeof(RetentionRuleSettings))]
[JsonSerializable(typeof(HostSettings))]
[JsonSerializable(typeof(HostAuditPolicySettings))]
[JsonSerializable(typeof(HttpsSettings))]
[JsonSerializable(typeof(ProviderSettings))]
[JsonSerializable(typeof(ProviderSettings[]))]
[JsonSerializable(typeof(AiProviderKind))]
[JsonSerializable(typeof(ModelEntry))]
[JsonSerializable(typeof(ModelReasoningSettings))]
[JsonSerializable(typeof(ReasoningCapabilities))]
[JsonSerializable(typeof(ReasoningControlSupport))]
[JsonSerializable(typeof(ReasoningWireDialect))]
[JsonSerializable(typeof(ReasoningEffortLevel))]
[JsonSerializable(typeof(ReasoningOutputMode))]
[JsonSerializable(typeof(ReasoningContentSegment))]
[JsonSerializable(typeof(WorkspaceCheckExecutableCatalogSettings))]
[JsonSerializable(typeof(WorkspaceCheckExecutableSettings))]
[JsonSerializable(typeof(WorkspaceCheckProfileSettings))]
[JsonSerializable(typeof(WorkspaceCheckProfileOptionSettings))]
[JsonSerializable(typeof(WorkspaceCheckKind))]
[JsonSerializable(typeof(WorkspaceCheckDiagnosticParserKind))]
[JsonSerializable(typeof(Dictionary<string, WorkspaceCheckProfileSettings>))]
[JsonSerializable(typeof(Dictionary<string, WorkspaceCheckProfileOptionSettings>))]
[JsonSerializable(typeof(Dictionary<string, string[]>))]
[JsonSerializable(typeof(CliSettings))]
[JsonSerializable(typeof(ArcanumTheme))]
[JsonSerializable(typeof(SecuritySettings))]
[JsonSerializable(typeof(WardPolicySettings))]
[JsonSerializable(typeof(GuardrailsPolicySettings))]
[JsonSerializable(typeof(GuardrailsAuditPolicySettings))]
[JsonSerializable(typeof(DaemonSettings))]
[JsonSerializable(typeof(UnseenServantJob))]
[JsonSerializable(typeof(UnseenServantJob[]))]
[JsonSerializable(typeof(List<UnseenServantJob>))]
[JsonSerializable(typeof(ConfigurationValidationError))]
[JsonSerializable(typeof(ConfigurationValidationError[]))]
[JsonSerializable(typeof(LogLevel))]
[JsonSerializable(typeof(WorkspaceSettings))]
[JsonSerializable(typeof(FeatureSettings))]
[JsonSerializable(typeof(IntegrationSettings))]
[JsonSerializable(typeof(A2AIntegrationSettings))]
[JsonSerializable(typeof(CommLinkIntegrationSettings))]
[JsonSerializable(typeof(EmbeddingIntegrationSettings))]
[JsonSerializable(typeof(McpIntegrationSettings))]
[JsonSerializable(typeof(WebResearchIntegrationSettings))]
[JsonSerializable(typeof(WorkspaceCheckIntegrationSettings))]
[JsonSerializable(typeof(ExecutionSettings))]
[JsonSerializable(typeof(CostSettings))]
[JsonSerializable(typeof(BudgetPolicySettings))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(JsonSchemaDefinition))]
[JsonSerializable(typeof(JsonSchemaDefinition[]))]
[JsonSerializable(typeof(List<JsonSchemaDefinition>))]
[JsonSerializable(typeof(PricingSettings))]
[JsonSerializable(typeof(ModelPricingEntry))]
[JsonSerializable(typeof(ModelPricingEntry[]))]
[JsonSerializable(typeof(List<ModelPricingEntry>))]
[JsonSerializable(typeof(Dictionary<string, ModelPricingEntry>))]

public partial class ConfigurationJsonContext : JsonSerializerContext;
