using System.Text.Json.Serialization;
using RetroDownfall.Arcanum.Core.Configuration;
using RetroDownfall.Arcanum.Core.Logging;
using RetroDownfall.Arcanum.Core.Primitives;

namespace RetroDownfall.Arcanum.Core.Serialization;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, WriteIndented = true)]
[JsonSerializable(typeof(ArcanumConfigurationFile))]
[JsonSerializable(typeof(ArcanumSettings))]
[JsonSerializable(typeof(HostSettings))]
[JsonSerializable(typeof(ServerSettings))]
[JsonSerializable(typeof(HostRateLimitSettings))]
[JsonSerializable(typeof(HostAuditLogSettings))]
[JsonSerializable(typeof(HttpsSettings))]
[JsonSerializable(typeof(ProviderSettings))]
[JsonSerializable(typeof(ProviderSettings[]))]
[JsonSerializable(typeof(AiProviderKind))]
[JsonSerializable(typeof(ModelEntry))]
[JsonSerializable(typeof(ConclaveSettings))]
[JsonSerializable(typeof(ConclaveA2ASettings))]
[JsonSerializable(typeof(IntelligenceSettings))]
[JsonSerializable(typeof(PerceptionSettings))]
[JsonSerializable(typeof(SpellSettings))]
[JsonSerializable(typeof(CampaignsSettings))]
[JsonSerializable(typeof(CliSettings))]
[JsonSerializable(typeof(ArcanumTheme))]
[JsonSerializable(typeof(ThemeColors))]
[JsonSerializable(typeof(ThemeSemanticColors))]
[JsonSerializable(typeof(SecuritySettings))]
[JsonSerializable(typeof(DaemonSettings))]
[JsonSerializable(typeof(UnseenServantJob))]
[JsonSerializable(typeof(UnseenServantJob[]))]
[JsonSerializable(typeof(List<UnseenServantJob>))]
[JsonSerializable(typeof(CommLinkSettings))]
[JsonSerializable(typeof(GrimoireSettings))]
[JsonSerializable(typeof(EventBusSettings))]
[JsonSerializable(typeof(ConfigurationValidationError))]
[JsonSerializable(typeof(ConfigurationValidationError[]))]
[JsonSerializable(typeof(LogSettings))]
[JsonSerializable(typeof(LogLevel))]
[JsonSerializable(typeof(WorkspaceSettings))]
[JsonSerializable(typeof(SessionSettings))]
[JsonSerializable(typeof(WardSettings))]
[JsonSerializable(typeof(ApprenticeSettings))]
[JsonSerializable(typeof(CodexSettings))]
[JsonSerializable(typeof(ProvingGroundsSettings))]
[JsonSerializable(typeof(McpSettings))]
[JsonSerializable(typeof(PromptSettings))]
[JsonSerializable(typeof(MetricsSettings))]
[JsonSerializable(typeof(ResilienceSettings))]
[JsonSerializable(typeof(EmbeddingSettings))]
[JsonSerializable(typeof(ScryingSettings))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(JsonSchemaDefinition))]
[JsonSerializable(typeof(JsonSchemaDefinition[]))]
[JsonSerializable(typeof(List<JsonSchemaDefinition>))]
[JsonSerializable(typeof(StructuredOutputSettings))]
[JsonSerializable(typeof(PricingSettings))]
[JsonSerializable(typeof(ModelPricingEntry))]
[JsonSerializable(typeof(ModelPricingEntry[]))]
[JsonSerializable(typeof(List<ModelPricingEntry>))]
[JsonSerializable(typeof(Dictionary<string, ModelPricingEntry>))]
[JsonSerializable(typeof(BudgetSettings))]
[JsonSerializable(typeof(WebBrowsingSettings))]

[JsonSerializable(typeof(ClientToolForwardingSettings))]

[JsonSerializable(typeof(GuardrailsSettings))]

[JsonSerializable(typeof(GuardrailsAuditLogSettings))]

public partial class ConfigurationJsonContext : JsonSerializerContext;
