using Microsoft.Data.Sqlite;

using RetroDownfall.Arcanum.Core.Covenant;
using RetroDownfall.Arcanum.Core.Memory;
using RetroDownfall.Arcanum.Infrastructure.Data.Schema;

namespace RetroDownfall.Arcanum.Infrastructure.Data.Covenant;

/// <summary>Whether a plan run measures its targets or removes them.</summary>
internal enum CovenantArtifactPlanMode
{
    /// <summary>Counts each target's rows with the predicate <see cref="Delete"/> would remove them by.</summary>
    Count = 1,

    /// <summary>Removes each target's rows and reports how many went.</summary>
    Delete = 2,
}

/// <summary>What one plan run found or removed, target by target.</summary>
/// <param name="Targets">
/// Every projection in plan order, then the artifact table when the plan has one, each table exactly
/// once. A target the run skipped — gated off by the Core version, or a conditional mirror that is
/// absent or unreachable — reports zero. The sum is the whole count; no consumer appends the artifact
/// table again.
/// </param>
/// <param name="VectorMirror">The plan's one conditional mirror as the catalog shows it, or absent.</param>
/// <param name="ArtifactRows">
/// The artifact target's own entry, which is always <c>Targets[^1]</c> when the plan has an artifact,
/// and zero for a plan that has none.
/// </param>
internal sealed record CovenantArtifactPlanTally(
    IReadOnlyList<MemoryErasureTableCount> Targets,
    SagaVectorMirrorKind VectorMirror,
    long ArtifactRows);

/// <summary>
/// Runs one artifact kind's projections and artifact target, in either mode, on the caller's
/// connection and transaction.
/// </summary>
/// <remarks>
/// The live erasure kernel and the staged restore purge both delete through this, and a plan's preflight
/// counts through it, so the predicate that measures a target is the one that removes it. Two copies of
/// the loop are how a count and a delete come to disagree about which rows an artifact owns.
///
/// <para>It never begins, authorizes, or commits, never touches <c>artifact_sensitivity</c>, and never
/// catches <see cref="SqliteException"/>. Each of those belongs to the caller: the transaction and the
/// authorization are the caller's evidence that the delete was allowed, the label is the caller's record
/// of what the artifact was, and a missing declared table is an integrity failure the caller has to see
/// rather than a target this runner may quietly skip. Only the conditional mirrors, which no schema file
/// installs, are classified and skipped when they are not a plain table.</para>
///
/// <para>Only <c>$artifactKey</c> is bound. Every projection and artifact statement is generated by
/// <see cref="CovenantArtifactPurgeTarget"/> against that one normalised parameter; a pointer delete or a
/// redaction that binds other identities stays with its consumer.</para>
/// </remarks>
internal static class CovenantArtifactPlanRunner
{
    internal static async Task<CovenantArtifactPlanTally> RunAsync(
        SqliteConnection connection,
        SqliteTransaction? transaction,
        SensitiveArtifactKind kind,
        string artifactKey,
        CovenantArtifactPlanMode mode,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(connection);

        ArgumentException.ThrowIfNullOrEmpty(artifactKey);

        if (mode is not (CovenantArtifactPlanMode.Count or CovenantArtifactPlanMode.Delete))
        {
            throw new ArgumentOutOfRangeException(nameof(mode), mode, "A plan runs in Count or Delete mode.");
        }

        CovenantArtifactPurgePlan plan = CovenantArtifactPurgePlans.Resolve(kind);

        List<MemoryErasureTableCount> targets = new(plan.Projections.Count + 1);

        SagaVectorMirrorKind vectorMirror = SagaVectorMirrorKind.Absent;

        // Read at the first gated target and then reused, so a run sees one Core version. Read lazily
        // rather than up front so a plan with no gated target never needs the metadata at all, while a
        // plan that has one still fails on missing or malformed metadata instead of guessing.
        int? coreVersion = null;

        foreach (CovenantArtifactPurgeTarget target in plan.Projections)
        {
            if (target.RequiredFromCoreVersion is { } requiredVersion)
            {
                coreVersion ??= await GrimoireCoreSchemaVersion
                    .ReadAsync(connection, cancellationToken, transaction)
                    .ConfigureAwait(false);

                if (coreVersion < requiredVersion)
                {
                    targets.Add(new MemoryErasureTableCount(target.Table, 0));

                    continue;
                }
            }

            if (target.ExistsConditionally)
            {
                vectorMirror = await SagaVectorMirror
                    .ClassifyAsync(connection, transaction, target.Table, cancellationToken)
                    .ConfigureAwait(false);

                if (vectorMirror is not SagaVectorMirrorKind.PlainTable)
                {
                    targets.Add(new MemoryErasureTableCount(target.Table, 0));

                    continue;
                }
            }

            targets.Add(new MemoryErasureTableCount(
                target.Table,
                await RunTargetAsync(connection, transaction, target, artifactKey, mode, cancellationToken)
                    .ConfigureAwait(false)));
        }

        long artifactRows = 0;

        if (plan.Artifact is { } artifact)
        {
            artifactRows = await RunTargetAsync(connection, transaction, artifact, artifactKey, mode, cancellationToken)
                .ConfigureAwait(false);

            targets.Add(new MemoryErasureTableCount(artifact.Table, artifactRows));
        }

        return new CovenantArtifactPlanTally(targets, vectorMirror, artifactRows);
    }

    private static async Task<long> RunTargetAsync(
        SqliteConnection connection,
        SqliteTransaction? transaction,
        CovenantArtifactPurgeTarget target,
        string artifactKey,
        CovenantArtifactPlanMode mode,
        CancellationToken cancellationToken)
    {
        await using SqliteCommand command = connection.CreateCommand();

        command.Transaction = transaction;

        command.CommandText = mode == CovenantArtifactPlanMode.Count
            ? target.CountBy("$artifactKey")
            : target.DeleteBy("$artifactKey");

        _ = command.Parameters.AddWithValue("$artifactKey", artifactKey);

        if (mode == CovenantArtifactPlanMode.Delete)
        {
            return await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        // A count(*) always answers with an integer. Anything else is refused rather than read as zero,
        // because a count that defaulted to zero would prove an absence nobody observed.
        return await command.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false) is long rows
            ? rows
            : throw new InvalidDataException($"The count over {target.Table} did not return an integer.");
    }
}
